version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'pip'
    directory: '/processing'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/front'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/audio'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/campaign'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/visualisation'
    schedule:
      interval: 'weekly'
